### ISSUE TITLE
How can I install pg_protobuf extension on Postgresql 10/11 ?

### ISSUE THREAD

**Issue by marufoglu** [afiskon/pg_protobuf#1]
Hi,
When I run in order of " make , makeinstall, makeinstall " commands at terminal , 

it says "No Target"

 or 

"Makefile:14: /usr/lib64/pgsql/pgxs/src/makefiles/pgxs.mk: No such file or directory make: *** No rule to make target `/usr/lib64/pgsql/pgxs/src/makefiles/pgxs.mk'.  Stop."

What should I do ? 

Please help
Thanks

**Comment by afiskon** [comment]
Could you please provide exact versions of PostgreSQL and your OS?

**Comment by marufoglu** [comment]
OS is Centos7 1810 and PG version is 11.4
Thanks

**Comment by marufoglu** [comment]
Any idea ?

**Comment by afiskon** [comment]
Sorry that it took that long to reply.

I've tested that the extension works just fine with modern versions of PostgreSQL.

The issue that you had is most likely related to the fact that you were missing a -dev package of PostgreSQL which contains all necessary C headers, Makefiles, etc. In Ubuntu the package is named something like `postgresql-server-dev-13`. Most likely it has the same name in CentOS if you are using official packages from the PostgreSQL community.

I've updated the README to make the steps of installing the extension more clear. Please let me know if the problem is still actual.
